apiVersion: v1
kind: ConfigMap
metadata:
  name: im-config
data:
  MYSQL_HOST: "mysql"
  MYSQL_PORT: "3306"
  REDIS_HOST: "redis"
  REDIS_PORT: "6380"
  REDIS_PASS: "123456"
  VERIFY_HOST: "verify-server"
  VERIFY_PORT: "50051"
  STATUS_HOST: "status-server"
  STATUS_PORT: "50052"
  CHAT_HOST: "chat-server"
  SELF_HOST: "chat-server"
  SELF_PORT: "8090"
  SELF_RPC_PORT: "50055"
