apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-server
  template:
    metadata:
      labels:
        app: status-server
    spec:
      containers:
        - name: status-server
          image: im-status-server:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 50052
          envFrom:
            - configMapRef:
                name: im-config
---
apiVersion: v1
kind: Service
metadata:
  name: status-server
spec:
  selector:
    app: status-server
  ports:
    - port: 50052
      targetPort: 50052
