FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y python3 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY build_release/bin/chat_server .
COPY ChatServer/ChatServer/config.ini ./config_chat1.ini
COPY ChatServer/entrypoint.sh .
COPY libs/ /usr/local/lib/
RUN ldconfig /usr/local/lib && chmod +x entrypoint.sh chat_server

EXPOSE 8090 50055
ENTRYPOINT ["./entrypoint.sh"]
